name: instantly_sdk
description: The unofficial SDK for the Instantly API.
version: 0.0.2
repository: https://github.com/a-wallen/instantly_sdk_dart.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
dependencies:
  dio: ^5.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
